# [100 numpy exercises](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_no_solution.md)

In [0]:
"""
1. Import the numpy package under the name np (★☆☆)
"""

import numpy as np

In [2]:
"""
2. Print the numpy version and the configuration (★☆☆)
"""

print(np.__version__)
print(np.__config__.show())

1.14.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


In [3]:
"""
3. Create a null vector of size 10 (★☆☆)
"""

Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
"""
4. How to find the memory size of any array (★☆☆)
"""

from sys import getsizeof

"""
getsizeofとnbytesの値が違うのは、
getsizeofはオブジェクト全体のメモリサイズ、
nbytesはオブジェクトの中身のメモリサイズを返すから
"""
print(getsizeof(Z))
print(Z.nbytes) # nbytes = .size * .itemsize
print(Z.size)
print(Z.itemsize)

176
80
10
8


In [5]:
"""
5. How to get the documentation of the numpy add function from the command line? (★☆☆)¶
"""

# $ python -c "import numpy; numpy.info(numpy.add)

'\n5. How to get the documentation of the numpy add function from the command line? (★☆☆)¶\n'

In [6]:
"""
6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
"""

Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
"""
7. Create a vector with values ranging from 10 to 49 (★☆☆)
"""

Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
"""
8. Reverse a vector (first element becomes last) (★☆☆)
"""

reversed_Z = Z[::-1]
print(reversed_Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [9]:
"""
9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
"""

Z = np.arange(0, 9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
"""
10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
"""

non_zero = np.nonzero([1, 2, 0, 0, 4, 0])
print(non_zero)

(array([0, 1, 4]),)


In [11]:
"""
11. Create a 3x3 identity matrix (★☆☆)
"""

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
"""
12. Create a 3x3x3 array with random values (★☆☆)
"""

Z = np.random.random([3, 3, 3])
print(Z)

[[[0.64256374 0.40116307 0.65180769]
  [0.59569308 0.20358354 0.80155093]
  [0.03800725 0.28579976 0.78740065]]

 [[0.68888892 0.02494898 0.25060637]
  [0.81982232 0.70028478 0.78652318]
  [0.07411821 0.66980793 0.10786778]]

 [[0.16763431 0.81604328 0.41059016]
  [0.44261774 0.45359133 0.37418498]
  [0.27447152 0.0545794  0.13172349]]]


In [13]:
"""
13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
"""

Z = np.random.random([10, 10])
min_Z, max_Z = Z.min(), Z.max()

print(min_Z, max_Z)

0.0028231078852545277 0.9684257156276341


In [14]:
"""
14. Create a random vector of size 30 and find the mean value (★☆☆)
"""

Z = np.random.random([30, 30])
mean_Z = Z.mean()

print(mean_Z)

0.4980707382184567


In [15]:
"""
15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
"""

Z = np.ones([5, 5])
Z[1:-1, 1:-1] = 0

print(Z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
"""
16. How to add a border (filled with 0's) around an existing array? (★☆☆)
"""

# https://stackoverflow.com/questions/35751306/python-how-to-pad-numpy-array-with-zeros

Z = np.ones([5, 5])
np.pad(Z, 1, mode="constant")

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [17]:
"""
17. What is the result of the following expression? (★☆☆)

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

"""

print("0 * np.nan: ", 0 * np.nan)
print("np.inf > np.nan: ", np.inf > np.nan)
print("np.nan - np.nan:", np.nan - np.nan)
print("0.3 == 3 * .1: ", 0.3 == 3 * .1)

0 * np.nan:  nan
np.inf > np.nan:  False
np.nan - np.nan: nan
0.3 == 3 * .1:  False


In [18]:
"""
18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
"""

np.diag(np.arange(4)+1, k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [19]:
"""
19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
"""

Z = np.zeros([8, 8])
Z[::2, ::2] = 1
Z[1::2, 1::2] = 1
print(Z)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [20]:
"""
20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
"""

np.unravel_index(100, (6, 7, 8)) # 100番目の要素を3次元配列の中での位置で返す

(1, 5, 4)

In [21]:
"""
21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
"""

# https://docs.scipy.org/doc/numpy/reference/generated/numpy.tile.html

np.tile([[0, 1], [1, 0]], (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [22]:
"""
22. Normalize a 5x5 random matrix (★☆☆)
"""

Z = np.random.random([5, 5])
min_Z, max_Z = Z.min(), Z.max()

norm_Z = (Z - min_Z) / (max_Z - min_Z)
print(norm_Z)

[[0.00621206 0.4681444  0.61034701 0.13556671 0.43480842]
 [0.57651728 0.17073536 0.06810044 0.070327   0.        ]
 [0.11040905 0.66202834 0.65791216 0.15614134 0.90835861]
 [0.92683583 0.80441217 0.07500154 0.65274658 1.        ]
 [0.59564255 0.96972979 0.85048063 0.12116722 0.8671048 ]]


In [23]:
# よくわからないのでスキップ

"""
23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
"""

color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [24]:
"""
24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
"""

a, b = np.random.random([5, 3]), np.random.random([3, 2])
a.dot(b)

array([[0.21404688, 0.22318288],
       [0.31844851, 0.16034268],
       [0.26390828, 0.21149854],
       [0.30848391, 0.68888579],
       [0.43224857, 0.7054394 ]])

In [25]:
"""
25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
"""

Z = np.arange(10)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


In [26]:
"""

26. What is the output of the following script? (★☆☆)

# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
"""

print(sum(range(5), -1)) # 4 + 3 + 2
from numpy import *
print(sum(range(5), -1)) # 4 + 3 + 2 + 1

9
10


In [27]:
"""
27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
"""
Z = np.arange(5)

print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: ignored

In [6]:
"""
28. What are the result of the following expressions?

np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
"""

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-9.22337204e+18]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in floor_divide
  # Remove the CWD from sys.path while we load stuff.


In [20]:
"""
29. How to round away from zero a float array ? (★☆☆)
round away form zeroは小数点以下切り上げ
"""

Z = np.random.uniform(-10, 10, 10)
print(Z)
Z_1 = np.abs(Z)
print(Z)
Z_2 = np.ceil(np.abs(Z_1))
print(Z_2)
Z_3 = np.copysign(Z_2, Z)
print(Z)

"""
np.abs()は絶対値を返す
np.ceil()小数点以下切り上げ
np.copysign()は一番目の引数に与えた要素の符号を二番目の引数で与えた要素の符号に変える。0は0
"""

[ 7.67865857  5.58960893  5.12274646  1.22742659  3.99335947  2.74585133
  7.29991326 -9.34806555  5.85985343  8.49949765]
[ 7.67865857  5.58960893  5.12274646  1.22742659  3.99335947  2.74585133
  7.29991326 -9.34806555  5.85985343  8.49949765]
[ 8.  6.  6.  2.  4.  3.  8. 10.  6.  9.]
[ 7.67865857  5.58960893  5.12274646  1.22742659  3.99335947  2.74585133
  7.29991326 -9.34806555  5.85985343  8.49949765]


'\nnp.abs()は絶対値を返す\nnp.ceil()小数点以下切り上げ\nnp.copysign()は一番目の引数に与えた要素の符号を二番目の引数で与えた要素の符号に変える。0は0\n'

In [22]:
"""
30. How to find common values between two arrays? (★☆☆)
"""

a = np.arange(5)
b = np.arange(2, 8)

print(a)
print(b)

common = np.intersect1d(a, b)
print(common)

[0 1 2 3 4]
[2 3 4 5 6 7]
[2 3 4]
